\hypertarget{classdjango_1_1contrib_1_1gis_1_1geoip2_1_1base_1_1_geo_i_p2_exception}{}\doxysection{django.\+contrib.\+gis.\+geoip2.\+base.\+Geo\+IP2\+Exception Class Reference}
\label{classdjango_1_1contrib_1_1gis_1_1geoip2_1_1base_1_1_geo_i_p2_exception}\index{django.contrib.gis.geoip2.base.GeoIP2Exception@{django.contrib.gis.geoip2.base.GeoIP2Exception}}


Inheritance diagram for django.\+contrib.\+gis.\+geoip2.\+base.\+Geo\+IP2\+Exception\+:
% FIG 0


Collaboration diagram for django.\+contrib.\+gis.\+geoip2.\+base.\+Geo\+IP2\+Exception\+:
% FIG 1


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/django/contrib/gis/geoip2/base.\+py\end{DoxyCompactItemize}
