\hypertarget{classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_g_d_a_l_exception}{}\doxysection{django.\+contrib.\+gis.\+gdal.\+error.\+GDALException Class Reference}
\label{classdjango_1_1contrib_1_1gis_1_1gdal_1_1error_1_1_g_d_a_l_exception}\index{django.contrib.gis.gdal.error.GDALException@{django.contrib.gis.gdal.error.GDALException}}


Inheritance diagram for django.\+contrib.\+gis.\+gdal.\+error.\+GDALException\+:
% FIG 0


Collaboration diagram for django.\+contrib.\+gis.\+gdal.\+error.\+GDALException\+:
% FIG 1


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/\+Lib/site-\/packages/django/contrib/gis/gdal/error.\+py\end{DoxyCompactItemize}
